version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "db_sudarsono"
      MYSQL_USER: "sudarsono"
      MYSQL_PASSWORD: "sono07032024"
      MYSQL_ROOT_PASSWORD: "sono07032024"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "sono07032024"
    depends_on:
      - db

volumes:
  dbdata:
